[project]
name = "time-audit"
requires-python = "^3.13"
dependencies = [
    "streamlit>=1.42.0",
    "supabase>=2.13.0",
    "python-dotenv>=1.0.1",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
black = ">=25.1.0"
